In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import * 
import matplotlib.pyplot as plt

##### Load the OCR letter recognition dataset, Link
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/letter-recognition/letter-recognition.data'
dataset = pd.read_csv(url, header=None)

In [2]:
# Load the OCR letter recognition dataset
url = 'letter-recognition.data'
df = pd.read_csv(url, header=None)

In [3]:
# Split the dataset into features and labels
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [4]:
# Encode the labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [6]:
print(X_train)

[[ 3  8  4 ...  8  6  8]
 [ 5 11  7 ...  7  8  8]
 [ 6 10  9 ...  8  6  7]
 ...
 [ 7  9  6 ...  8  3  4]
 [ 3  1  4 ...  5  2  8]
 [ 4  8  5 ... 10  3  5]]


In [7]:
X_train = X_train / 15.0
X_test = X_test / 15.0

In [8]:
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(16,)))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(26, activation='softmax'))

In [9]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics =['accuracy'])

In [10]:
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=12)

Epoch 1/50
1334/1334 [==============================] - 3s 2ms/step - loss: 2.6791 - accuracy: 0.2015 - val_loss: 1.7879 - val_accuracy: 0.5525
Epoch 2/50
1334/1334 [==============================] - 2s 1ms/step - loss: 1.8780 - accuracy: 0.4096 - val_loss: 1.3666 - val_accuracy: 0.6320
Epoch 3/50
1334/1334 [==============================] - 3s 2ms/step - loss: 1.6152 - accuracy: 0.4874 - val_loss: 1.1957 - val_accuracy: 0.6842
Epoch 4/50
1334/1334 [==============================] - 2s 1ms/step - loss: 1.4797 - accuracy: 0.5354 - val_loss: 1.0997 - val_accuracy: 0.6933
Epoch 5/50
1334/1334 [==============================] - 2s 1ms/step - loss: 1.3857 - accuracy: 0.5632 - val_loss: 1.0180 - val_accuracy: 0.7085
Epoch 6/50
1334/1334 [==============================] - 3s 2ms/step - loss: 1.3221 - accuracy: 0.5811 - val_loss: 0.9683 - val_accuracy: 0.7245
Epoch 7/50
1334/1334 [==============================] - 3s 2ms/step - loss: 1.2575 - accuracy: 0.6047 - val_loss: 0.9317 - val_accuracy:

In [11]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test accuracy:", accuracy)
print("Test loss:", loss)

125/125 [==============================] - 0s 1ms/step - loss: 0.5422 - accuracy: 0.8325
Test accuracy: 0.8324999809265137
Test loss: 0.5421750545501709


In [12]:
model.save('ocr_model.h5')
# Save the trained model

In [13]:
from tensorflow.keras.models import load_model
model = load_model('ocr_model.h5')
# Load the trained model

In [14]:
sample_records = X_test[:1000]
# Select a few records for classification

In [15]:
# Perform classification
predictions = model.predict(sample_records)

In [16]:
predicted_labels = np.argmax(predictions, axis=1)

In [17]:
predicted_letters = label_encoder.inverse_transform(predicted_labels)
actual_letters = label_encoder.inverse_transform(y_test)

In [18]:
# Print the predicted labels and corresponding actual labels
print("Predicted Labels\tActual Labels")
for i in range(len(predicted_letters)):
    print(f"{predicted_letters[i]}\t\t\t{actual_letters[i]}")

Predicted Labels	Actual Labels
D			D
D			D
V			V
B			B
H			H
N			N
R			E
Q			Q
E			R
N			N
Q			Q
W			O
N			N
D			D
J			I
M			M
U			U
S			S
O			O
A			A
X			X
A			A
K			K
S			S
O			O
V			V
Y			Y
J			J
D			D
V			V
D			D
V			V
K			K
T			F
N			N
I			I
G			G
T			T
H			H
K			K
J			J
O			O
M			M
T			T
B			B
Q			Q
Z			Z
C			C
D			D
X			X
K			C
G			G
Q			Q
F			F
N			N
Y			Y
Z			Z
K			K
C			C
K			T
M			M
W			V
G			G
R			M
D			D
T			T
H			H
P			P
N			N
C			C
O			O
X			X
X			X
Q			Q
V			V
F			P
V			V
G			G
W			W
O			H
P			P
O			O
I			I
G			G
X			X
Y			X
Y			P
W			W
Q			Q
D			D
D			N
G			Q
T			T
T			T
V			V
Y			Y
I			T
V			V
J			J
M			U
D			D
L			L
M			M
Y			Y
E			E
M			M
A			A
Y			Y
K			K
Y			Y
U			U
U			U
U			U
K			C
Q			Q
I			I
A			A
E			E
B			D
T			T
B			P
Q			Q
Z			Z
G			G
X			X
G			G
F			F
M			M
S			S
E			E
E			E
K			K
Z			Z
K			X
O			O
E			E
G			U
I			I
R			R
O			O
M			M
J			J
F			F
K			K
M			M
N			N
U			T
D			D
H			H
R			R
L			L
Z			Z
F			F
V			V
W			W
E			E
T			T
W			W
Y			Y
Q			Q
L			L
F		